#!/bin/bash

#Configuration set-up
echo .
echo Configuration Wifi en cours ...
echo .
echo ..
ip link set wlan0 down 
iw dev | grep wlan
ip link set wlan0 up
iw wlan0 scan | grep Archos10
iw dev wlan0 connect Archos10
echo ..
echo .
dhclient wlan0
echo Configuration Wifi OK ...
echo .
echo .
echo Configuration CAN en cours ...
echo .
echo ..
echo -e "\tInterface can0" 
sudo ifconfig can0 down | grep vide 
canconfig can0 bitrate 500000 ctrlmode triple-sampling on | grep bitrate
echo ..
echo .
sudo ifconfig can0 up
#RAZ des donnees CAN enregistrees lors d une session anterieur
rm -f can.log
echo Configuration CAN OK ...
#ls -l
echo 
echo 
echo ------- Service ON  
#Lancement de l'application java udpsender_graphic_can
java -jar /usr/ELA/ela-demo.jar &

#Lancement de l'ecoute du reseau CAN sur can0, filtre sur ID 301
candump can0 --filter=0x301:0x301 > ./can.log &

